apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: app
build:
  insecureRegistries:
    - 192.168.100.189:5000
  artifacts:
    - image: 192.168.100.189:5000/apps/demo
      custom:
        buildCommand: mvn spring-boot:build-image -DskipTests=true -Dspring-boot.build-image.imageName=%IMAGE% && docker push %IMAGE%
        dependencies:
          paths:
          - pom.xml
          - src/main/resources
          - target/classes
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          - src: "target/classes/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: target/classes/
deploy:
  kubeContext: minikube
  kustomize:
    paths:
      - "src/k8s/demo/"

        #portForward:
        #  - resourceType: pod
        #    resourceName: app
        #    port: 8080 #
        #    localPort: 8080 # *Optional*
