apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: apps/demo
        name: app
        env:
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "*"
        - name: JAVA_OPTS
          value: -Dspring.main.lazy-initialization=true -noverify -XX:TieredStopAtLevel=1
          #          value: -Dspring.main.lazy-initialization=true -noverify -XX:TieredStopAtLevel=1  -agentlib:jdwp=transport=dt_socket,suspend=n,server=y,address=50005
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
