apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: app
images:
  - name: apps/demo
    newName: 192.168.100.189:5000/apps/demo
resources:
- deployment.yaml
transformers:
- github.com/dsyer/docker-services/layers/actuator?ref=HEAD
